service: email-api

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4500
    lambdaPort: 4502

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: send
          method: post
          cors: true

